version: '3.9'

services:
  registration-api:
    build:
      context: ./registration-api
      dockerfile: src/Registration.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  registration-web:
    build:
      context: ./registration-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    depends_on:
      - registration-api